import markUrl from "../assets/noending-mark.svg";

// Official NoEnding mark from docs/NoEnding-logo.svg (tight-viewBox variant).
// Vector scales freely — no multi-size assets needed inside the webview;
// multi-size raster sets (icns/ico) are generated by `tauri icon` for bundling.
export default function SidebarLogo({
  size = 22,
  animated = false,
}: {
  size?: number;
  /** One-time reveal on the home hero (respects prefers-reduced-motion). */
  animated?: boolean;
  /** Deprecated: the official asset carries the brand color (#111111). */
  color?: string;
}) {
  const h = size;
  const w = size * (769 / 569); // trimmed viewBox aspect ratio
  return (
    <img
      src={markUrl}
      width={Math.round(w)}
      height={h}
      alt="NoEnding"
      className={animated ? "mark-reveal" : undefined}
      draggable={false}
    />
  );
}
